version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: festiva-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: festiva-api
